---
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - "{{ groups['pdc'][0] }}"
      - "{{ groups['rdc'][0] }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required

- name: Install DHCP Service
  ansible.windows.win_feature:
    name: DHCP
    state: present
    include_management_tools: yes
  
# Use Windows Powershell to configure DHCP Service
- name: Configure DHCP Scope
  win_shell: Add-DhcpServerV4Scope -Name "DHCPScope" -StartRange 10.175.128.185 -EndRange 10.175.128.190 -SubnetMask 255.255.255.192
- name: Configure DHCP DNS
  win_shell: Set-DhcpServerV4OptionValue -DnsServer 10.175.128.180 -Router 10.175.128.129
- name: Configure DHCP Lease Duration
  win_shell: Set-DhcpServerv4Scope -ScopeId 10.175.128.185 -LeaseDuration 1.00:00:00
- name: Restart DHCP service
  win_shell: Restart-service dhcpserver
- #name: Add DHCP as Authorized Server
  #win_shell: Add-DhcpServerInDC -DnsName AJB52-DHCP.ajb2.local -IPAddress 10.175.128.183